name: Run tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        neovim_version: ["v0.10.0", "nightly"]

    steps:
      - uses: actions/checkout@v3
      - name: Setup neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: ${{ matrix.neovim_version }}
      - name: Run tests
        run: |
          make test
